"""Add details JSON column to DailySummary

Revision ID: aa2ba423b4e7
Revises: e3ed1f036267
Create Date: 2026-07-28 21:16:45.728806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa2ba423b4e7'
down_revision: Union[str, None] = 'e3ed1f036267'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_summaries', sa.Column('details', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_summaries', 'details')
    # ### end Alembic commands ###
